### ISSUE TITLE
Missing "config.script" file

### ISSUE THREAD

**Issue by LiamM32** [BlueMagnificent/Urho3D_CodeBlocks_Wizard#1]
The "config.script" file referenced in the Readme does not exist.

**Comment by BlueMagnificent** [comment]
Which platform are you running on?

**Comment by LiamM32** [comment]
I'm on Linux.  I'm sorry about for opening this issue, as it was my dumb mistake.  I was looking in the "urho3d" folder of this project, not the file that I already had.  Yes, I have the config.script file in my "codeblocks/templates/wizard" folder.
