### ISSUE TITLE
Not working with Code::Blocks on Linux

### ISSUE THREAD

**Issue by LiamM32** [BlueMagnificent/Urho3D_CodeBlocks_Wizard#2]
I put this into the right directory where all the Code::Blocks wizards are located ("_/usr/share/codeblocks/templates/wizard/_").  But when I run Code::Blocks and try to make a new project, there is not option for Urho3D.

**Comment by BlueMagnificent** [comment]
Is this related to #1  ?
If so would like to note that the project (as is) was actually meant for Windows platform with the MinGW compiler toolset. 
It would be nice to have it accommodate other platforms and even compilers that code::blocks and Urho3D both support. This might not be a commitment for now, however contributions are welcomed.

**Comment by LiamM32** [comment]
Yeah... sorry about that.  After I realized and fixed my mistake, the option is now showing-up.  I haven't tested it with a new project yet though.
I'm going away now, so it will be some time before I have my desktop computer back to try this out.
